server:
  port: 8092
  servlet:
    context-path: /control-historial-clinico

spring:
  application:
    name: Local instance MySQL80
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/control_sistemas
    username: root
    password: Trivellari13
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
