server:
  port: 8072

spring:
  application:
    name: gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: get-control-pacientes
          uri: lb://control-pacientes
          predicates:
            - Path=/control-pacientes/**
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/error
        - id: get-control-historial-clinico
          uri: lb://control-historial-clinico
          predicates:
            - Path=/control-historial-clinico/**
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/error
        - id: get-control-citas
          uri: lb://control-citas
          predicates:
            - Path=/control-citas/**
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/error
        - id: get-control-sistemas
          uri: lb://control-sistemas
          predicates:
            - Path=/control-sistemas/**
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/error
        - id: get-control-reportes
          uri: lb://control-reportes
          predicates:
            - Path=/control-reportes/**
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/error
        - id: get-email-service
          uri: lb://email-service
          predicates:
            - Path=/email-service/**
          filters:
            - name: CircuitBreaker
              args:
                name: CircuitBreaker
                fallbackUri: forward:/error

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true