spring:
  application:
    name: config-service

  cloud:
    config:
      server:
        git:
          uri: https://github.com/DanielVallado/Sistema-clinico.git
          search-paths: config-data
          default-label: master

server:
  port: 8070
